AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: binx-og-image-generator
      Description: 'binx-og-image-generator builder'
      ServiceRole: !Ref 'ProjectRole'
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: TWINE_USERNAME
            Value: __token__
            Type: PLAINTEXT
          - Name: TWINE_PASSWORD
            Value: /twine/binx-og-image-generator
            Type: PARAMETER_STORE
      Source:
        Type: GITHUB
        Location: https://github.com/binxio/og-image-generator.git
        BuildSpec: .buildspec.yaml
        GitCloneDepth: 0
      Triggers:
        FilterGroups:
         -  - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: "refs/tags/.*"
        Webhook: true

  ProjectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codebuild.amazonaws.com
            Condition: {}
      Path: /
      Policies:
        - PolicyName: BinxOgImageGeneratorBuilder
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: 
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/twine/binx-og-image-generator'
              - Effect: Allow
                Action:
                  - ec2:DescribeRegions
                Resource: 
                  - '*'
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - '*'

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/codebuild/${Project}'
      RetentionInDays: 7

