name: release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/og-binx-image-generator
    if: github.event.base_ref == 'refs/heads/master' || github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.13
      - name: checkout
        run: git fetch --prune --unshallow
      - name: install environment
        run: pip install pipenv setuptools build && pipenv sync -d
      - name: build
        run: pipenv run make dist
      - name: upload to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: dist/
